# Generated by Django 3.1.4 on 2020-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20201215_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['surname'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTRO')], default='O', max_length=10, verbose_name='Género'),
        ),
    ]
