# Generated by Django 3.1.4 on 2020-12-16 19:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20201216_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=70, verbose_name='Descripción')),
                ('size', models.CharField(blank=True, default='', max_length=4, verbose_name='Telle')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio producto')),
                ('today_date', models.DateField(default=datetime.datetime.now, verbose_name='Creación')),
                ('due_date', models.DateField(default=datetime.datetime.now, verbose_name='Vencimiento')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produccion/%Y/%m/%d', verbose_name='Imagen')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.category', verbose_name='Tipo prenda')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.estados', verbose_name='Estado Producción')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'db_table': 'production',
                'ordering': ['-id'],
            },
        ),
    ]
