# Generated by Django 3.1.4 on 2021-01-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20201223_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categorysize',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Telle'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='category',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Tipo de Prenda'),
        ),
    ]
